services:
  backend:
    build: ./backend
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000,http://192.168.125.100:3000
    # restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://192.168.125.100:5000
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend
